/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package La_Prosperidad;

import java.awt.Color;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Bodega extends javax.swing.JFrame {
    public static float ventas_totales = 0;
    public static float compras_totales[];
    public static DefaultTableModel tabla;
    public static Object[][] actualizacion;
    public static int contador_devoluciones;
    public static int devoluciones_totales;
    public static int identificacion_vector[] =new int[100];
     private static Integer p = null;  
     int N = 0;
     private DefaultTableModel dtm ;
     private Object[] o = new Object[5];
     int tienda [][] = new int [1][5]; 
     int t[] = new int [1] ;
     private int cod ;
     
     
 
     
     
    /**
     * Creates new form Bodega
     */
    public Bodega() {
        initComponents();
        getContentPane().setBackground(Color.decode("#f6eee8"));
        setLocationRelativeTo(null);
        dtm = (DefaultTableModel) Bodega_matriz.getModel();
        
        float ventas_totales = 0;
        Compras.ventas_totales = ventas_totales;
        
        int a = 0;
        Factura.a = a;
        Compras.a = a;
        Devoluciones.a = a;
        Tarjeta.a = a;
        Tarjeta.identificacion_vector = identificacion_vector;
        
        int b = 0;
        Devoluciones.b = b;
        
        boolean condicion = true;
        while(condicion == true){
            try{
                p = Integer.valueOf(JOptionPane.showInputDialog("Ingrese el valor inicial de su negocio"));
                if (p == null) {
                    JOptionPane.showMessageDialog(null, "Operación cancelada.", "Información", JOptionPane.INFORMATION_MESSAGE);
                    condicion = false;
                }
                if (p < 0) {
                    JOptionPane.showMessageDialog(null, "Monto no válido. Debe ser mayor o igual a 0.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                } else {
                    condicion = false;
                }
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Monto no valido", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        }

        dinero.setText(Integer.toString(p));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Bodega_matriz = new javax.swing.JTable();
        Añadir = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        ventas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        compras = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        n_devoluciones = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dinero = new javax.swing.JTextField();
        Salir = new javax.swing.JButton();
        Actualizar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        total_devoluciones = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        n_compras = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        Cliente = new javax.swing.JMenu();
        Comprar = new javax.swing.JMenuItem();
        Devolver = new javax.swing.JMenuItem();
        Amigo_Frecuente = new javax.swing.JMenuItem();
        Registros = new javax.swing.JMenu();
        Ventas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel1.setText("ALMACEN - LA PROSPERIDAD");

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel2.setText("BODEGA");

        Bodega_matriz.setBackground(new java.awt.Color(204, 255, 255));
        Bodega_matriz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Código", "Estado", "Unidades", "Precio por unidad"
            }
        ));
        jScrollPane1.setViewportView(Bodega_matriz);

        Añadir.setBackground(new java.awt.Color(171, 132, 194));
        Añadir.setText("Añadir");
        Añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirActionPerformed(evt);
            }
        });

        Eliminar.setBackground(new java.awt.Color(171, 132, 194));
        Eliminar.setText("Sacar de circulación");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        ventas.setEditable(false);
        ventas.setBackground(new java.awt.Color(230, 212, 225));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel4.setText("Total ventas");

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel5.setText("Total compras");

        compras.setEditable(false);
        compras.setBackground(new java.awt.Color(230, 212, 225));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel6.setText("N° devoluciones");

        n_devoluciones.setEditable(false);
        n_devoluciones.setBackground(new java.awt.Color(230, 212, 225));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel7.setText("N° compras");

        dinero.setEditable(false);
        dinero.setBackground(new java.awt.Color(230, 212, 225));
        dinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dineroActionPerformed(evt);
            }
        });

        Salir.setBackground(new java.awt.Color(171, 132, 194));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        Actualizar.setBackground(new java.awt.Color(171, 132, 194));
        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel9.setText("Total devoluciones");

        total_devoluciones.setEditable(false);
        total_devoluciones.setBackground(new java.awt.Color(230, 212, 225));
        total_devoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_devolucionesActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel8.setText("Total en caja");

        n_compras.setEditable(false);
        n_compras.setBackground(new java.awt.Color(230, 212, 225));
        n_compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_comprasActionPerformed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(230, 212, 225));

        Cliente.setText("Cliente");

        Comprar.setBackground(new java.awt.Color(153, 153, 255));
        Comprar.setText("Compras");
        Comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarActionPerformed(evt);
            }
        });
        Cliente.add(Comprar);

        Devolver.setText("Devoluciones");
        Devolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevolverActionPerformed(evt);
            }
        });
        Cliente.add(Devolver);

        Amigo_Frecuente.setText("Tarjeta \"Amigo Frecuente\"");
        Amigo_Frecuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Amigo_FrecuenteActionPerformed(evt);
            }
        });
        Cliente.add(Amigo_Frecuente);

        jMenuBar1.add(Cliente);

        Registros.setText("Registros");

        Ventas.setBackground(new java.awt.Color(230, 212, 225));
        Ventas.setText("Ventas");
        Ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentasActionPerformed(evt);
            }
        });
        Registros.add(Ventas);

        jMenuBar1.add(Registros);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(Añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(Eliminar)
                .addGap(65, 65, 65)
                .addComponent(Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(103, 103, 103)
                                            .addComponent(jLabel5))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(34, 34, 34)
                                            .addComponent(jLabel7)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(n_devoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(total_devoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ventas, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                        .addComponent(compras, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                                .addComponent(dinero, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(n_compras, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(298, 298, 298))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Salir)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ventas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(compras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(total_devoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n_devoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(n_compras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(dinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Eliminar)
                    .addComponent(Actualizar)
                    .addComponent(Añadir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Salir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarActionPerformed
        Compras frame = new Compras();
        frame.setVisible(true);
    }//GEN-LAST:event_ComprarActionPerformed

    private void DevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevolverActionPerformed
        Devoluciones.tienda = tienda;
        Devoluciones frame = new Devoluciones();
        frame.setVisible(true);;
    }//GEN-LAST:event_DevolverActionPerformed

    private void Amigo_FrecuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Amigo_FrecuenteActionPerformed
        Tarjeta frame = new Tarjeta();
        frame.setVisible(true);
    }//GEN-LAST:event_Amigo_FrecuenteActionPerformed
    
    float compras_totales_ = 0;  
    void ord (int codigo_c, int cantidad_producto, int precio) {
        
        if (N >= t.length) {    
            t = Arrays.copyOf(t, t.length * 2);
        }
        
        int i =0;
        while ( i < N  && codigo_c > tienda[i][1] ) {
             i++;
        }
        
        for (int j = N; j > i; j--) {
            tienda[j][0] = tienda[j - 1][0];
            tienda[j][1] = tienda[j - 1][1];
            tienda[j][2] = tienda[j - 1][2];
            tienda[j][3] = tienda[j - 1][3];
            tienda[j][4] = tienda[j - 1][4];
            if( tienda[j - 1][2] == 1 ) {
                t[j] = t[j-1];
            }   
        }
        
        tienda[i][0] = N + 1;
        tienda[i][1] = codigo_c;
        tienda[i][2]= 1;
        tienda[i][3] = cantidad_producto;
        tienda[i][4] = precio; 
        n_compras.setText(String.valueOf(N+1));

        t[i] = codigo_c ;
        
         N++;        
    }

    
    void actualizarTabla() {
        dtm.setRowCount(0);
        for (int i = 0; i < N; i++) {
            dtm.addRow(new Object[]{tienda[i][0], tienda[i][1], tienda[i][2], tienda[i][3],tienda[i][4] });
            Compras.tienda = tienda;
        }
    }
    
     
    public void enviar_cod (int cod) {
        this.cod = cod ; 
        cambiarEstado( cod);
        actualizarTabla();  
    }
    
    private void cambiarEstado(int codigoProducto) {
        int j=0 ;
        boolean productoEncontrado = false; 

        for (int i = 0; i < N; i++) {
            if (tienda[i][1] == codigoProducto) {
                tienda[i][2] = 0; 
                productoEncontrado = true;
                j = i;
                JOptionPane.showMessageDialog(null, "El estado del producto con código " + codigoProducto + " ha sido cambiado a inactivo (0).", "Información", JOptionPane.INFORMATION_MESSAGE);
                break;
            }
        }

        if (productoEncontrado == false ) {
            JOptionPane.showMessageDialog(null, "El estado del producto con código " + N + " ha sido cambiado a inactivo (0).", "Información", JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(null, "El producto con código " + codigoProducto + " no fue encontrado.", "Error", JOptionPane.ERROR_MESSAGE); //Por si acaso aparece el 0 que vi por ahí
        }
    }
            
    private void VentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentasActionPerformed
        Registros_ventas frame = new Registros_ventas();
        frame.setVisible(true);
    }//GEN-LAST:event_VentasActionPerformed

    private void n_comprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_comprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n_comprasActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        float caja;

        dtm.setRowCount(0);
        for (Object[] row : actualizacion) {
            dtm.addRow(row);
        }
        Bodega_matriz.setModel(dtm);

        ventas.setText("$ " + String.valueOf(ventas_totales));
        n_devoluciones.setText(String.valueOf(contador_devoluciones + 1));
        total_devoluciones.setText("-$ " + String.valueOf(devoluciones_totales));
        caja = (float) p;
        caja = caja + ventas_totales - devoluciones_totales;
        dinero.setText("$ " + String.valueOf(caja));
    }//GEN-LAST:event_ActualizarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void dineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dineroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dineroActionPerformed

    private void total_devolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_devolucionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_devolucionesActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        Sacar_de_circulación c = new  Sacar_de_circulación(this);
        c.setVisible(true);
        c.Recibir_matriz(t);
    }//GEN-LAST:event_EliminarActionPerformed

    private void AñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirActionPerformed
        boolean productoExiste = false;

        try{
            if(N >= tienda.length){
                tienda = Arrays.copyOf(tienda, tienda.length * 2);
                for (int i = N; i < tienda.length; i++) {
                    tienda[i] = new int[5];
                }   
            }

            int codigo_c =  Integer.parseInt(JOptionPane.showInputDialog("Digita el código") );
            while(codigo_c < 0){
                JOptionPane.showMessageDialog(null, "Codigo " + codigo_c + " no valido", "Advertencia", JOptionPane.WARNING_MESSAGE);
                codigo_c =  Integer.parseInt(JOptionPane.showInputDialog("Digita el código.") );
            }

            for (int i = 0; i < N; i++) {
                if (tienda[i][1] == codigo_c) {
                    productoExiste = true;
                    break;
                }
            }
            
            if (productoExiste) {
                JOptionPane.showMessageDialog(null, "El producto con el código " + codigo_c + " ya está registrado.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int cantidad_producto = Integer.parseInt(JOptionPane.showInputDialog("Digita la cantidad del producto.(Min 5)") );

            while (cantidad_producto < 5) {
                JOptionPane.showMessageDialog(null, "Te agradeceríamos que ingreses al menos 5 unidades del producto. ¡Gracias!", "Advertencia", JOptionPane.WARNING_MESSAGE );
                cantidad_producto = Integer.parseInt(JOptionPane.showInputDialog("Vuelve a digitar la cantidad del producto.(Min 5) ") );
            }

            double precio_c = Double.parseDouble( JOptionPane.showInputDialog("Ingrese el precio por unidad en que compro el producto"))  ;

            while (precio_c < 0) {
                JOptionPane.showMessageDialog(null, "Te agradeceríamos que ingreses número valido para el precio. ¡Gracias!", "Advertencia", JOptionPane.WARNING_MESSAGE );
                precio_c = Integer.parseInt(JOptionPane.showInputDialog("Vuelve a digitar el precio.") );
            }

            int  precio =  (int)  ( precio_c +  (precio_c * 0.2)) ;
            int t =  (int) (cantidad_producto * precio_c)  ;

            if ( (p-t) >= 0 ){
                p = p - t;
                dinero.setText("$ " + Integer.toString(p));
                compras_totales_ += t;
                compras.setText("$ " + String.valueOf(compras_totales_));
                ord( codigo_c, cantidad_producto, precio);
                actualizarTabla();
            } else {
                JOptionPane.showMessageDialog(null, "No hay suficiente dinero en caja para compar más mercancia. ¡Intente de nuevo!", "Advertencia", JOptionPane.WARNING_MESSAGE );
            }
            Devoluciones.p = p;

        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor, ingresa valores numéricos válidos.", "Advertencia", JOptionPane.WARNING_MESSAGE ); //
        }
    }//GEN-LAST:event_AñadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bodega().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JMenuItem Amigo_Frecuente;
    private javax.swing.JButton Añadir;
    private javax.swing.JTable Bodega_matriz;
    private javax.swing.JMenu Cliente;
    private javax.swing.JMenuItem Comprar;
    private javax.swing.JMenuItem Devolver;
    private javax.swing.JButton Eliminar;
    private javax.swing.JMenu Registros;
    private javax.swing.JButton Salir;
    private javax.swing.JMenuItem Ventas;
    private javax.swing.JTextField compras;
    private javax.swing.JTextField dinero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField n_compras;
    private javax.swing.JTextField n_devoluciones;
    private javax.swing.JTextField total_devoluciones;
    private javax.swing.JTextField ventas;
    // End of variables declaration//GEN-END:variables
}
