/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package La_Prosperidad;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Devoluciones extends javax.swing.JFrame {
    public static int [][]tienda;
    public static int a;
    public static int b;
    public static int p;
    /**
     * Creates new form Devoluciones
     */
    public Devoluciones() {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.decode("#f6eee8"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        leer_codigo2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        leer_codigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        leer_unidades = new javax.swing.JTextField();
        Devolver_producto = new javax.swing.JButton();
        Finalizar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        leer_identificacion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        leer_nombre = new javax.swing.JTextField();

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel3.setText("COMPRAS");

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel1.setText("CÓDIGO: ");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel4.setText("DEVOLUCIONES");

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel5.setText("PRODUCTO: ");

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel2.setText("CÓDIGO: ");

        leer_codigo.setBackground(new java.awt.Color(230, 212, 225));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel6.setText("UNIDADES: ");

        leer_unidades.setBackground(new java.awt.Color(230, 212, 225));

        Devolver_producto.setBackground(new java.awt.Color(171, 132, 194));
        Devolver_producto.setText("Devolver producto");
        Devolver_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Devolver_productoActionPerformed(evt);
            }
        });

        Finalizar.setBackground(new java.awt.Color(171, 132, 194));
        Finalizar.setText("Finalizar");
        Finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel7.setText("CLIENTE:");

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel8.setText("NOMBRE:");

        leer_identificacion.setBackground(new java.awt.Color(230, 212, 225));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel9.setText("IDENTIFICACIÓN: ");

        leer_nombre.setBackground(new java.awt.Color(230, 212, 225));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(leer_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Devolver_producto))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Finalizar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(leer_unidades, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(leer_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(leer_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(leer_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(leer_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leer_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(leer_unidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Finalizar)
                    .addComponent(Devolver_producto))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void Devolver_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Devolver_productoActionPerformed
        int devoluciones_totales;
        String nombre;
        int identificacion, codigo, unidades, contador_devoluciones;
        
        int[] vector_codigos = new int[tienda.length];
        for (int i = 0; i < tienda.length; i++) {
            vector_codigos[i] = tienda[i][1];
        }
        
        int aux, min;
        for (int j = 0; j < (vector_codigos.length - 1); j++) {
            min = j;
            for (int k = j+1; k < vector_codigos.length; k++) {
                if(vector_codigos[min] > vector_codigos[k]){
                    min = k;
                }
            }
            aux = vector_codigos[j];
            vector_codigos[j] = vector_codigos[min];
            vector_codigos[min] = aux;
        }     
        
        try{
            nombre = leer_nombre.getText();
            identificacion = Integer.parseInt(leer_identificacion.getText());
            codigo = Integer.parseInt(leer_codigo.getText());
            unidades = Integer.parseInt(leer_unidades.getText());
            leer_codigo.setText("");
            leer_unidades.setText("");
            
            if((identificacion < 0)||(codigo < 0)||(unidades < 0)){
                JOptionPane.showMessageDialog(null, "DATOS NEGATIVOS NO VÁLIDOS", "ERROR", JOptionPane.ERROR_MESSAGE);
                leer_nombre.setText("");
                leer_identificacion.setText("");
            }else{
                int inf, sup, med;
                med = 0;
                boolean busqueda;
                inf = 0;
                sup = vector_codigos.length - 1;
                busqueda = false;
                while(inf <= sup && !busqueda){
                    med = (inf+sup)/2;
                    if (codigo == vector_codigos[med]) {
                        busqueda = true;
                    }else{
                        if (codigo > vector_codigos[med]) {
                            inf = med + 1;
                        }else{
                            sup = med - 1;
                        }
                    }
                }
                
                int pos = 0;
                for (int i = 0; i < vector_codigos.length; i++) {
                    if(tienda[i][1] == vector_codigos[med]){
                        pos = i;
                    }
                }
                
                if (busqueda == false) {
                    JOptionPane.showMessageDialog(null, "CODIGO NO ENCONTRADO", "ERROR", JOptionPane.ERROR_MESSAGE);
                }else{
                    if(tienda[pos][2] == 0){
                        JOptionPane.showMessageDialog(null, "PRODUCTO FUERA DE CIRCULACION", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
                    }else{
                        if(tienda[pos][1] == codigo){
                            b +=  unidades*tienda[pos][4];
                            if(b > p){
                                JOptionPane.showMessageDialog(null, "DEVOLUCIÓN REALIZADA SIN ÉXITO: FONDOS INSUFICIENTES", "ERROR", JOptionPane.ERROR_MESSAGE);
                            }else{
                                devoluciones_totales = b;
                                Bodega.devoluciones_totales = devoluciones_totales;
                                JOptionPane.showMessageDialog(null, "PRODUCTO DEVUELTO CON ÉXITO", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
                                Object[][] actualizacion = new Object[tienda.length][tienda[0].length];
                                for (int i = 0; i < tienda.length; i++) {
                                    for (int j = 0; j < tienda[i].length; j++) {
                                        actualizacion[i][j] = tienda[i][j];
                                    }
                                }
                                Bodega.actualizacion = actualizacion;
                            }
                        }
                    }
                }
            }
            
            contador_devoluciones = a++;
            Bodega.contador_devoluciones = contador_devoluciones;
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "TIPO DE DATOS INVÁLIDOS", "ERROR", JOptionPane.ERROR_MESSAGE);
            leer_nombre.setText("");
            leer_identificacion.setText("");
            leer_codigo.setText("");
            leer_unidades.setText("");
        }
    }//GEN-LAST:event_Devolver_productoActionPerformed

    private void FinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarActionPerformed
        this.dispose();
    }//GEN-LAST:event_FinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Devoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Devoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Devoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Devoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Devoluciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Devolver_producto;
    private javax.swing.JButton Finalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField leer_codigo;
    private javax.swing.JTextField leer_codigo2;
    private javax.swing.JTextField leer_identificacion;
    private javax.swing.JTextField leer_nombre;
    private javax.swing.JTextField leer_unidades;
    // End of variables declaration//GEN-END:variables
}
